	else if (mname == "ctf2")
	{
		SpawnWaypointNum('16 -621.1 193.4', -1, 0, us);
		SpawnWaypointNum('16 -527.2 197.5', -1, 0, us);
		SpawnWaypointNum('335.8 -986.7  40.0', 5, -1, us);
		SpawnWaypointNum('320.1 -191.3  40.0', 5, -1, us);
		SpawnWaypointNum('296.6 -1033.2 40', 5, 1, us);
		SpawnWaypointNum('190 -944.8 40', 5, 2, us);
		SpawnWaypointNum('188.2 -851.4 40', 5, 3, us);
		SpawnWaypointNum('90.6 -132.6 40', 14, 1, us);
		SpawnWaypointNum('201.1 -230.9 40', 14, 2, us);
		SpawnWaypointNum('199.5 -301.8 40', 14, 3, us);
		SpawnWaypointNum('269.6 -1262.4 -88', 5, 1, us);
		SpawnWaypointNum('193.6 -1176.2 -88', 5, 2, us);
		SpawnWaypointNum('192.5 -934.8 -88', 5, 3, us);
		SpawnWaypointNum('190.5 -853.9 -112', 5, 4, us);
		SpawnWaypointNum('116.7 81.4 -88', 14, 1, us);
		SpawnWaypointNum('205.7 8.4 -88', 14, 2, us);
		SpawnWaypointNum('190.8 -240.2 -88', 14, 3, us);
		SpawnWaypointNum('195.4 -321.7 -101', 14, 4, us);
		SpawnWaypointNum('257.2 -596 131', 5, 4, us);
		SpawnWaypointNum('310.1 -1264.3 40', 5, 0, us);
		SpawnWaypointNum('71.1 71.5 40', 14, 0, us);
		SpawnWaypointNum('16.0 -621.1 193.4', -1, 0, us);
		SpawnWaypointNum('16.0 -527.2 197.5', -1, 0, us);
		return TRUE;
	}
