	else if (mname == "ctf3")
	{
		SpawnWaypointNum('-1547.1 -508.7 417.0', 5, -1, us);
		SpawnWaypointNum('1457.0 498.0 417.0', 5, -1, us);
		SpawnWaypointNum('-1649.9 9.5 136', 5, 0, us);
		SpawnWaypointNum('-1546 -7 136', 5, 1, us);
		SpawnWaypointNum('-1303 -191.2 153', 5, 2, us);
		SpawnWaypointNum('-828.3 18.5 216', 5, 3, us);
		SpawnWaypointNum('-603 4.1 168', 5, 5, us);
		SpawnWaypointNum('-471.2 162.3 136', 5, 6, us);
		SpawnWaypointNum('1299.2 197.2 153', 14, 2, us);
		SpawnWaypointNum('822.9 -15.2 216', 14, 3, us);
		SpawnWaypointNum('1533.9 -1 136', 14, 1, us);
		SpawnWaypointNum('1652.4 -15.6 136', 14, 0, us);
		SpawnWaypointNum('730.5 -9.2 216', 14, 4, us);
		SpawnWaypointNum('526.7 0.5 136', 14, 5, us);
		SpawnWaypointNum('523 150.8 136', 14, 6, us);
		SpawnWaypointNum('-731.1 0.4 216', 5, 4, us);
		SpawnWaypointNum('-1343.4 0.8 200.0', -1, 0, us);
		SpawnWaypointNum('-1260.1 0.5 -404.0', -1, 1, us);
		SpawnWaypointNum('-1152.2 6.2 -408.0', -1, 2, us);
		SpawnWaypointNum('-1055.0 -2.6 -216.0', -1, 3, us);
		SpawnWaypointNum('-710.6 -15.3 -264.0', -1, 4, us);
		SpawnWaypointNum('-270.0 -3.8 -328.0', -1, 5, us);
		SpawnWaypointNum('1344.6 -1.1 200.0', -1, 0, us);
		SpawnWaypointNum('1267.0 -4.8 -346.0', -1, 1, us);
		SpawnWaypointNum('1054.6 -2.9 -216.0', -1, 3, us);
		SpawnWaypointNum('823.3 -0.8 -216.0', -1, 4, us);
		SpawnWaypointNum('250.1 -4.7 -328.0', -1, 5, us);
		SpawnWaypointNum('1165.1 0.0 -408.0', -1, 2, us);
		return TRUE;
	}
