	else if (mname == "e1m7")
	{
		SpawnWaypointNum('-499.8  80.9  72.0', 14, 0, us);
		SpawnWaypointNum('-391.7  79.8 248.0', 14, 1, us);
		SpawnWaypointNum('1022.7  61.1 188.0', 5, 0, us);
		SpawnWaypointNum('-238.9  67.4 252.0', 14, 2, us);
		SpawnWaypointNum('-246.9 -221.4 248.0', 14, 3, us);
		SpawnWaypointNum('991.4 -234.9 232.0', 5, 1, us);
		SpawnWaypointNum('558.8 -243.0 232.0', 5, 2, us);
		SpawnWaypointNum('157.7 -231.9 232.0', 14, 4, us);
		return TRUE;
	}
