	else if ((mname == "martim5") || (mname == "martim5c"))
	{
		SpawnWaypointNum('1169.2 135.4 40.0', 14, 1, us);
		SpawnWaypointNum('560.8 120.5 40.0', 14, 2, us);
		SpawnWaypointNum('555.2 700.0 40.0', 14, 3, us);
		SpawnWaypointNum('895.5 704.0 40.0', 14, 4, us);
		SpawnWaypointNum('892.8 1637.6 40.0', 14, 5, us);
		SpawnWaypointNum('519.9 1648.9 40.0', 14, 6, us);
		SpawnWaypointNum('530.5 1280.4 40.0', 14, 7, us);
		return TRUE;
	}
